version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
